name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Dan"
    - uses: azure/container-actions/docker-login@master
         with:
           login-server: danlep0820.azurecr.io
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
    
       - run: |
           docker build . -t danlep0820.azurecr.io/githubbuild:${{ github.sha }}
           docker push danlep0820.azurecr.io/githubbuild:${{ github.sha }}
